### ISSUE TITLE
Bug: Can't use DecisionThresholdConvergence object

### ISSUE THREAD

**Issue by izagorac** [JuliaTrustworthyAI/TaijaParallel.jl#9]
When I try to run the `generate_counterfactual` function in parallel as shown in the image below, I get an error about the `Convergence` object.

Code:
<img width="754" alt="Screenshot 2024-04-17 at 21 04 02" src="https://github.com/JuliaTrustworthyAI/TaijaParallel.jl/assets/33690862/40edf128-dc70-4ae1-b588-54a7edcb493f">

Error:
<img width="951" alt="Screenshot 2024-04-17 at 21 04 32" src="https://github.com/JuliaTrustworthyAI/TaijaParallel.jl/assets/33690862/01a35b98-3e94-407c-bde0-faced4134ac7">

When I follow the stacktrace of the error it leads me to the `get_convergence_type` function in the `Convergence` module in the CounterfactualExplanations package. This function has 2 versions: one with `AbstractConvergence` as input and one with `Symbol` as input (see image below)

<img width="656" alt="Screenshot 2024-04-17 at 21 07 10" src="https://github.com/JuliaTrustworthyAI/TaijaParallel.jl/assets/33690862/79a8d6e4-428e-4cfb-81a0-51c043a3e7ee">

In my case, because I have created my own DecisionThresholdConvergence object, I would expect the first function to be called. However, for reason currently unknown to me, when the `@with_parallelizer` macro is used the function with the `Symbol` as input is being called. I've tested the same code without the macro and this works how it is supposed to.

@pat-alt is this enough information for someone to look into? If more details are necessary, please let me know. Solving this issue would really help me out :)

**Comment by pat-alt** [comment]
That's all I need and indeed a nasty little bug. I'm working on it, but metaprogramming is always a little tricky (at least for me). In the meantime, you should be able to use the `parallelize` function directly, instead of the macro.

**Comment by izagorac** [comment]
Thanks @pat-alt, this fixes the issue
